server:
  port: 5050

spring:
  datasource:
    url: jdbc:h2:mem:order_db
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true

config:
  product-service:
    host: ${PRODUCT_SERVICE_HOST:localhost}
    port: ${PRODUCT_SERVICE_PORT:5055}